#!/usr/bin/env python3
"""Migrate workspace_album rows into album and backfill workspace_album.album_id.

Workflow:
1. Add workspace_album.album_id (FK -> album.id) if missing.
2. Insert rows from workspace_album into album:
   - id: auto generated by SQLite.
   - uuid: generated by script.
   - studio_id: resolved by workspace_album.studio_name -> studio.name.
   - title: workspace_album.album_name.
   - same-name fields copied directly where available.
3. Write inserted album.id back to workspace_album.album_id.

Default mode is dry-run. Use --apply to persist changes.
"""

from __future__ import annotations

import argparse
import shutil
import sqlite3
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_DB = Path(__file__).resolve().parents[1] / "database" / "Curator.db"


@dataclass
class Stats:
    total_rows: int = 0
    inserted_rows: int = 0
    skipped_already_linked: int = 0


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def table_columns(conn: sqlite3.Connection, table: str) -> set[str]:
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return {str(row[1]) for row in rows}


def ensure_workspace_album_album_id_column(conn: sqlite3.Connection) -> bool:
    cols = table_columns(conn, "workspace_album")
    if "album_id" in cols:
        return False

    conn.execute("ALTER TABLE workspace_album ADD COLUMN album_id INTEGER REFERENCES album(id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_workspace_album_album_id ON workspace_album(album_id)")
    return True


def backup_db(db_path: Path) -> Path:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = db_path.with_name(f"{db_path.stem}.backup_before_workspace_album_migration_{ts}{db_path.suffix}")
    shutil.copy2(db_path, backup_path)
    return backup_path


def build_studio_map(conn: sqlite3.Connection) -> dict[str, int]:
    rows = conn.execute("SELECT id, name FROM studio").fetchall()
    studio_map: dict[str, int] = {}
    for row_id, name in rows:
        if not name:
            continue
        studio_map[str(name)] = int(row_id)
    return studio_map


def migrate_rows(conn: sqlite3.Connection, stats: Stats) -> None:
    studio_map = build_studio_map(conn)
    if not studio_map:
        raise RuntimeError("studio table is empty, cannot resolve studio_id")

    workspace_cols = table_columns(conn, "workspace_album")
    album_cols = table_columns(conn, "album")

    same_name_fields = sorted(
        (workspace_cols & album_cols)
        - {
            "id",
            "uuid",
            "studio_id",
            "title",
        }
    )

    # Always ensure audit fields are written for inserted rows.
    if "created_at" not in same_name_fields and "created_at" in album_cols:
        same_name_fields.append("created_at")
    if "updated_at" not in same_name_fields and "updated_at" in album_cols:
        same_name_fields.append("updated_at")

    select_sql = """
        SELECT id, studio_name, album_name, status_id, current_path, expected_path, album_id
        FROM workspace_album
        ORDER BY id
    """
    rows = conn.execute(select_sql).fetchall()
    stats.total_rows = len(rows)

    for row in rows:
        wa_id = int(row[0])
        studio_name = row[1]
        album_name = row[2]
        album_id = row[6]

        if album_id is not None:
            stats.skipped_already_linked += 1
            continue

        if studio_name not in studio_map:
            raise RuntimeError(
                f"studio not found in studio table: workspace_album.id={wa_id}, studio_name={studio_name!r}"
            )

        studio_id = studio_map[studio_name]
        row_uuid = str(uuid.uuid4())
        now_text = now_iso()

        insert_cols = ["uuid", "studio_id", "title"]
        insert_vals: list[object] = [row_uuid, studio_id, album_name]

        row_dict = {
            "id": wa_id,
            "studio_name": studio_name,
            "album_name": album_name,
            "status_id": row[3],
            "current_path": row[4],
            "expected_path": row[5],
            "album_id": row[6],
        }

        for field in same_name_fields:
            insert_cols.append(field)
            if field == "created_at":
                insert_vals.append(now_text)
            elif field == "updated_at":
                insert_vals.append(now_text)
            else:
                insert_vals.append(row_dict.get(field))

        placeholders = ", ".join("?" for _ in insert_cols)
        insert_sql = f"INSERT INTO album ({', '.join(insert_cols)}) VALUES ({placeholders})"
        cursor = conn.execute(insert_sql, tuple(insert_vals))
        new_album_id = int(cursor.lastrowid)

        conn.execute(
            "UPDATE workspace_album SET album_id = ? WHERE id = ?",
            (new_album_id, wa_id),
        )
        stats.inserted_rows += 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Add workspace_album.album_id, import workspace_album into album, backfill album_id"
    )
    parser.add_argument("--db", type=Path, default=DEFAULT_DB, help=f"SQLite DB path (default: {DEFAULT_DB})")
    parser.add_argument("--apply", action="store_true", help="Persist migration changes")
    parser.add_argument("--no-backup", action="store_true", help="Do not create backup before apply")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    db_path = args.db.expanduser().resolve()

    if not db_path.exists():
        print(f"ERROR: database not found: {db_path}")
        return 1

    if args.apply and not args.no_backup:
        backup_path = backup_db(db_path)
        print(f"[INFO] Backup created: {backup_path}")

    stats = Stats()

    conn = sqlite3.connect(db_path)
    try:
        conn.execute("PRAGMA foreign_keys = ON")
        conn.execute("BEGIN")

        added_column = ensure_workspace_album_album_id_column(conn)
        migrate_rows(conn, stats)

        if args.apply:
            conn.commit()
            print("[INFO] Migration status: APPLIED")
        else:
            conn.rollback()
            print("[INFO] Migration status: DRY-RUN (ROLLED BACK)")

        print(f"[INFO] workspace_album.album_id added: {'yes' if added_column else 'no'}")
        print(f"[INFO] workspace_album total rows: {stats.total_rows}")
        print(f"[INFO] inserted into album: {stats.inserted_rows}")
        print(f"[INFO] skipped already linked rows: {stats.skipped_already_linked}")

        with sqlite3.connect(db_path) as read_conn:
            wa_count = read_conn.execute("SELECT COUNT(*) FROM workspace_album").fetchone()[0]
            album_count = read_conn.execute("SELECT COUNT(*) FROM album").fetchone()[0]
            read_cols = table_columns(read_conn, "workspace_album")
            if "album_id" in read_cols:
                linked_count = read_conn.execute(
                    "SELECT COUNT(*) FROM workspace_album WHERE album_id IS NOT NULL"
                ).fetchone()[0]
            else:
                linked_count = 0
            print(f"[INFO] post-check workspace_album rows: {wa_count}")
            print(f"[INFO] post-check album rows: {album_count}")
            print(f"[INFO] post-check workspace_album linked rows: {linked_count}")

        return 0
    except Exception as exc:  # noqa: BLE001
        conn.rollback()
        print(f"ERROR: migration failed: {exc}")
        return 1
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
